### ISSUE TITLE
Can you help me?

### ISSUE THREAD

**Issue by Ganyu69** [Sorrow446/MOOV-DL#4]
C:\Users\xxxxx\Pictures\MOOV>moov-dl_x64.exe -u https://moov.hk/#/album/
VASB00364847A
Traceback (most recent call last):
  File "moov-dl.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "Cryptodome\Cipher\__init__.py", line 87, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "Cryptodome\Cipher\_mode_gcm.py", line 57, in <module>
  File "Cryptodome\Util\_raw_api.py", line 171, in load_pycryptodome_raw_lib
OSError: Cannot load native module 'Cryptodome.Util._galois'
[11620] Failed to execute script moov-dl

**Comment by Sorrow446** [comment]
Cryptodome doesn't play well with pyinstaller, so the binary is broken. You'll have to run from source until I fix that, sorry.

**Comment by Ganyu69** [comment]
thank you 😄
