### ISSUE TITLE
Can't download anything with my vpn

### ISSUE THREAD

**Issue by hintlou** [Sorrow446/MOOV-DL#5]
C:\Users\Administrator>C:\Users\Administrator\MOOV-DL\moov-dl_x86.exe -u https:/
/moov.hk/#/album/VAEP00521645A

 _____ _____ _____ _____     ____  __
|     |     |     |  |  |___|    \|  |
| | | |  |  |  |  |  |  |___|  |  |  |__
|_|_|_|_____|_____|\___/    |____/|_____|

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 696, in urlopen
  File "urllib3\connectionpool.py", line 964, in _prepare_proxy
  File "urllib3\connection.py", line 359, in connect
  File "urllib3\connection.py", line 502, in _connect_tls_proxy
  File "urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
  File "ssl.py", line 407, in wrap_socket
  File "ssl.py", line 817, in __init__
  File "ssl.py", line 1077, in do_handshake
  File "ssl.py", line 689, in do_handshake
ssl.SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:847)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 449, in send
  File "urllib3\connectionpool.py", line 756, in urlopen
  File "urllib3\util\retry.py", line 573, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='mtg.now.com', port=4
43): Max retries exceeded with url: /moov/api/user/loginstatuscheck (Caused by S
SLError(SSLError(1, '[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:847)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "moov-dl.py", line 297, in <module>
    auth()
  File "moov-dl.py", line 107, in auth
    if not client.auth(cfg['email'], cfg['password']):
  File "api\client.py", line 41, in auth
    'POST', 'user/loginstatuscheck', headers, data=data
  File "api\client.py", line 11, in make_call
    r = self.s.request(method, self.base + epoint, headers=headers, params=param
s, data=data)
  File "requests\sessions.py", line 542, in request
  File "requests\sessions.py", line 655, in send
  File "requests\adapters.py", line 514, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='mtg.now.com', port=443):
 Max retries exceeded with url: /moov/api/user/loginstatuscheck (Caused by SSLEr
ror(SSLError(1, '[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:847)'),))
[9120] Failed to execute script moov-dl

**Comment by Sorrow446** [comment]
Not recommended, but you can change this line in api/client.py.
From:
```python
r = self.s.request(method, self.base + epoint, headers=headers, params=params, data=data)```
To:
```python
r = self.s.request(method, self.base + epoint, headers=headers, params=params, data=data, verify=False)```

**Comment by hintlou** [comment]
Thanks.But it can't work.moov is unavailable in my country,China.Is it the reason I can't connect to moov even with VPN?

**Comment by Sorrow446** [comment]
It's might be a requests / urllib. Disabling verify like above should fix your issue.

**Comment by hintlou** [comment]
Solved.Done.Thank you very much~

**Comment by Sorrow446** [comment]
You're welcome.
